name: prerelease

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'RELEASE'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run git diff command
        run: |
          echo `git diff --name-only ed0b909b5e68a6107a7016cf045d6327386be004 5e3ebfaf877b45738bd995272a5ec2e7602f7237` 
      - uses: pipe-cd/actions-gh-release@fix-tag-version
        with:
          release_file: 'RELEASE'
          token: ${{ secrets.GITHUB_TOKEN }}
